import os
liga0_desliga1 = 0
while liga0_desliga1 == 0:
    os.system('cls' if os.name == 'nt' else 'clear')
    print('0 : Soma')
    print('1 : Subtração')
    print('2 : Multiplicação')
    print('3 : Divisão')
    print('4 : Exponenciação')
    print('\n')
    print('Escolha a operação que deseja realizar:')
    operacao = int(input())

    while operacao not in [0, 1, 2, 3, 4]:
        print('Erro: a operação selecionada é inválida')
        print('\n')
        print('0 : Soma')
        print('1 : Subtração')
        print('2 : Multiplicação')
        print('3 : Divisão')
        print('4 : Exponenciação')
        print('\n')
        print('Escolha a operação que deseja realizar:')
        operacao = input()

    if operacao == 0:
        print('\n')
        print('>>> + escolhida.')
        print('\n')
        print('Qual o primeiro valor?')
        n1 = float(input())
        print('Qual o segundo valor?')
        n2 = float(input())
        print('\n')
        print('{} + {} = {}'.format(n1,n2,n1+n2))
        print('\n')
        print('=========')
        print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
        liga0_desliga1 = int(input())
        while liga0_desliga1 not in [0, 1]:
            print('Erro: a opção selecionada é inválida')
            print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
            liga0_desliga1 = int(input())
    elif operacao == 1:
        print('\n')
        print('>>> - escolhida.')
        print('\n')
        print('Qual o primeiro valor?')
        n1 = float(input())
        print('Qual o segundo valor?')
        n2 = float(input())
        print('\n')
        print('{} - {} = {}'.format(n1,n2,n1-n2))
        print('\n')
        print('=========')
        print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
        liga0_desliga1 = int(input())
        while liga0_desliga1 not in [0, 1]:
            print('Erro: a opção selecionada é inválida')
            print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
            liga0_desliga1 = int(input())
    elif operacao == 2:
        print('\n')
        print('>>> * escolhida.')
        print('\n')
        print('Qual o primeiro valor?')
        n1 = float(input())
        print('Qual o segundo valor?')
        n2 = float(input())
        print('\n')
        print('{} * {} = {}'.format(n1,n2,n1*n2))
        print('\n')
        print('=========')
        print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
        liga0_desliga1 = int(input())
        while liga0_desliga1 not in [0, 1]:
            print('Erro: a opção selecionada é inválida')
            print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
            liga0_desliga1 = int(input())
    elif operacao == 3:
        print('\n')
        print('>>> / escolhida.')
        print('\n')
        print('Qual o primeiro valor?')
        n1 = float(input())
        print('Qual o segundo valor?')
        n2 = float(input())
        print('\n')
        print('{} / {} = {}'.format(n1,n2,n1/n2))
        print('\n')
        print('=========')
        print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
        liga0_desliga1 = int(input())
        while liga0_desliga1 not in [0, 1]:
            print('Erro: a opção selecionada é inválida')
            print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
            liga0_desliga1 = int(input())
    elif operacao == 4:
        print('\n')
        print('>>> ** escolhida.')
        print('\n')
        print('Qual o primeiro valor?')
        n1 = float(input())
        print('Qual o segundo valor?')
        n2 = float(input())
        print('\n')
        print('{} ** {} = {}'.format(n1,n2,n1**n2))
        print('\n')
        print('=========')
        print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
        liga0_desliga1 = int(input())
        while liga0_desliga1 not in [0, 1]:
            print('Erro: a opção selecionada é inválida')
            print('Deseja fazer outra operação? 0 - SIM, 1 - NÃO')
            liga0_desliga1 = int(input())
if liga0_desliga1 == 1:
    os._exit(0)